REPLACEMENTS = {
    "travis-ci": ["ci travis", "travis ci"],
    "laravel": ["laravel framework", "laravel php"],
    "php": ["php 7", "php 8"],
    "vue.js": ["vuejs", "vue js"],
    "c#": ["c #"],
    "ms sql server": ["sql sql server", "sql server", "microsoft server"],
    "ms office": ["microsoft office"],
    ".net core": ["net core"],
    ".net framework": ["net framework"],
    "java": ["java 8", "java 11", "java enterprise edition"],
    "iaas": ["infrastructure as code"],
    "tcp/ip": ["tcp ip"],
    "active directory": ["ad"],
    "a/b": ["a b"],
    "e-commerce": ["e commerce"],
    "golang": ["go"],
    "oracle": ["sql oracle"],
    "testing": ["development testing"],
    "apache hive": ["hive"],
    "apache hadoop": ["hadoop"],
    "apache kafka": ["kafka"],
    "rs-422": ["rs 422"],
    "scikit-learn": ["scikit learn", "scikit"],
    "linux": ["server linux"]
}
REMOVE = [
    "e", "an", "for business", "english", "foreign language", "improve products", "in training", "latin",
    "manager", "multitasking", "research and", "research markets", "spanish", "who", "a a", "and development",
    "and look", "energetic", "english", "integration", "long term", "make", "who", "work environment",
    "middleware", "hotline", "medical insurance", "on performance", "russian", "senior engineer", "software",
    "software engineer", "software engineers", "systemverilog", "technology and", "communication",
    "compilation optimization", "creative", "design and", "development and", "development testing", "eda",
    "electrical engineering", "storage cloud", "cart", "data engineer", "integration", "integration services",
    "master data", "sql server management studio", "transact sql"
]
