REPLACEMENTS = {
    "travis-ci": ["ci travis", "travis ci"],
    "laravel": ["laravel framework", "laravel php"],
    "php": ["php 7", "php 8"],
    "vue.js": ["vue", "vuejs", "vue js"],
    "angular.js": ["angular", "angularjs", "angular js"],
    "react.js": ["react", "reactjs", "react js"],
    "c#": ["c #"],
    "mssql server": ["sql sql server", "sql server", "microsoft server"],
    "ms office": ["microsoft office"],
    ".net core": ["net core"],
    ".net framework": ["net framework"],
    "java": ["java 8", "java 11", "java enterprise edition"],
    "iaas": ["infrastructure as code"],
    "tcp/ip": ["tcp ip"],
    "active directory": ["ad"],
    "a/b": ["a b"],
    "e-commerce": ["e commerce"],
    "golang": ["go"],
    "oracle": ["sql oracle"],
    "testing": ["development testing"],
    "apache hive": ["hive"],
    "apache hadoop": ["hadoop", "apache hadoo"],
    "apache kafka": ["kafka"],
    "rs-422": ["rs 422"],
    "redhat": ["red hat linux", "red hat"],
    "scikit-learn": ["scikit learn", "scikit"],
    "linux": ["server linux"],
    "apache hbase": ["hbase"],
    "apache cassandra": ["cassandra"],
    "verilog": ["systemverilog"],
    "apache airflow": ["airflow"],
    "u-boot": ["u boot"],
    "apache nifi": ["nifi"],
}

REMOVE = [
    "celta", "cae", "netconf",
    "linux kernel", "usb", "multimedia", "user space", "sata", "ethernet",
    "design and", "development and", "eda", "senior engineer", "software",
    "software engineer", "software engineers", "technology and", "e", "an", "for business",
    "foreign language", "improve products", "in training", "latin", "gnu linux",
    "manager", "multitasking", "research and", "research markets", "spanish", "a a", "and development",
    "and look", "energetic", "english", "integration", "long term", "make", "who", "work environment",
    "middleware", "hotline", "medical insurance", "on performance", "russian", "senior engineer", "software",
    "systemverilog", "communication",
    "compilation optimization", "creative", "development testing", "scrum", "middleware",
    "electrical engineering", "storage cloud", "cart", "data engineer", "integration services",
    "master data", "sql server management studio", "transact sql", "3gpp", "architecture patterns",
    "chef", "class diagram", "collaboration", "component diagram", "deployment diagram",
    "diagram er", "draw io", "element management system", "er diagram", "lte", "management system",
    "network management system", "patterns architecture", "sequence diagram", "solution architecture",
    "use case diagram", "message broker", "network management", "network architecture", "deep diving",
    "trello", "youtrack",
]
